apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-aws-query-service-quotas
spec:
  compositeTypeRef:
    apiVersion: example.io/v1alpha1
    kind: XAccount
  mode: Pipeline
  pipeline:
  - step: service-quotas
    functionRef:
      name: function-aws-query
    input:
      apiVersion: aws.fn.crossplane.io/v1beta1
      kind: Input
      queryType: ListServiceQuotas
      region: eu-central-1
      parameters:
        serviceCode: "ec2"
      target: status.ec2Quotas
    credentials:
    - name: aws-creds
      source: Secret
      secretRef:
        namespace: upbound-system
        name: aws-creds
